version: "3.3"
services:
  smilecdr:
    container_name: smile_cdr
    #image: docker.smilecdr.com/smilecdr:2022.02.R01  
    build:
      context: . 
      dockerfile: Dockerfile_smile
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9100:9100"
      - "8001:8001"
      - "9200:9200"
      - "9201:9201"
    environment:
      - POSTGRES_USER=${DB_SUPER_USER_ID}
      - POSTGRES_PASSWORD=${DB_SUPER_USER_PASSWORD}
      - POSTGRES_DB=${DB_SYS_NAME}
      - CDR_DB_NAME=${DB_CDR_NAME}
      - CDR_USER=${DB_CDR_USERID}
      - CDR_PASSWORD=${DB_CDR_PASSWORD}
    volumes:
      - log:/home/ubuntu/smilecdr/log
      - mq:/home/ubuntu/smilecdr/activemq-data
    restart: "unless-stopped"
    depends_on:
      - postgresdb
  postgresdb:
    #image: postgres:12.2
    build:
      context: . 
      dockerfile: Dockerfile_postgres
    container_name: postgres_cdr
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_SUPER_USER_ID}
      - POSTGRES_PASSWORD=${DB_SUPER_USER_PASSWORD}
      - POSTGRES_DB=${DB_SYS_NAME}
      - CDR_DB_NAME=${DB_CDR_NAME}
      - CDR_USER=${DB_CDR_USERID}
      - CDR_PASSWORD=${DB_CDR_PASSWORD}
    volumes:
      - db:/home/ubuntu/smilecdr/database
    restart: unless-stopped
  adminer:
    image: adminer
    container_name: adminer_cdr
    ports:
      - 8888:8080
    restart: unless-stopped
  pathling:
    image: aehrc/pathling:4
    container_name: pathling_cdr
    ports:
      - "8080:8080"
    environment:
      spark.executor.memory: 4g
      pathling.cors.allowedOrigins: http://localhost:8080
    restart: unless-stopped
    volumes:
      - pathling:/home/ubuntu/smilecdr/warehouse
volumes:
  log:
  mq:
  db:
  pathling:
