# Use base Smile CDR image as parent image
#FROM docker.smilecdr.com/smilecdr:2020.08.R02
#FROM docker.smilecdr.com/smilecdr:2021.11.R04
FROM docker.smilecdr.com/smilecdr:2022.02.R01 

# Set the smilecdr folder as working directory
WORKDIR /home/smile/smilecdr

# Copy modified properties file to the container.
copy ./cdr-config-Master-modified.properties ./classes/cdr-config-Master.properties

# Copy modified environment settings file to the container.
copy ./setenv-modified ./bin/setenv
